apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80  # The port the service will expose
      targetPort: 5000  # The port Flask app listens to
  type: LoadBalancer  # Expose the service externally (change to ClusterIP for internal only)
